version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8088:8088
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: achatdb
    volumes:
      - mysql_data:/var/lib/mysql
  spring-app:
    image: ratatouka/achat:0.92
    ports:
      - 8089:8089
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
volumes:
  mysql_data:
